# Generated by Django 4.2.30 on 2026-05-21 00:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key prevents enumeration attacks on the game endpoint.', primary_key=True, serialize=False)),
                ('deck_state', models.JSONField(default=list, help_text='Ordered list of remaining cards. Mutated on every draw.')),
                ('status', models.CharField(choices=[('BETTING', 'Betting'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('player_bet', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('outcome', models.CharField(blank=True, choices=[('WIN', 'Win'), ('LOSE', 'Lose'), ('PUSH', 'Push'), ('BLACKJACK', 'Blackjack (Natural)')], max_length=20, null=True)),
                ('payout', models.DecimalField(blank=True, decimal_places=2, help_text='Net P&L applied to player balance on completion. Negative means a loss.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='Level number (0-based). Also determines bot_count.', unique=True)),
                ('bot_count', models.IntegerField(help_text='Number of AI bots sharing the deck at this table.', validators=[django.core.validators.MinValueValidator(0)])),
                ('min_bet', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('max_bet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unlock_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum player balance required to access this table.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hand_type', models.CharField(choices=[('PLAYER', 'Player'), ('DEALER', 'Dealer'), ('BOT', 'Bot')], db_index=True, max_length=10)),
                ('bot_index', models.IntegerField(blank=True, help_text='0-indexed seat position. Set only for BOT hands; null for PLAYER and DEALER.', null=True)),
                ('cards', models.JSONField(default=list, help_text='List of card strings, e.g. ["AH", "KC", "7D"].')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('STAND', 'Stand'), ('BUST', 'Bust'), ('BLACKJACK', 'Blackjack')], default='ACTIVE', max_length=20)),
                ('is_soft', models.BooleanField(default=False, help_text='True when an Ace in the hand is counted as 11.')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='game.game')),
            ],
            options={
                'verbose_name': 'Hand',
                'verbose_name_plural': 'Hands',
                'ordering': ['hand_type', 'bot_index'],
            },
        ),
        migrations.CreateModel(
            name='GameEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('GAME_START', 'Game Start'), ('DEAL', 'Deal'), ('PLAYER_HIT', 'Player Hit'), ('PLAYER_STAND', 'Player Stand'), ('PLAYER_DOUBLE', 'Player Double Down'), ('PLAYER_BUST', 'Player Bust'), ('BOT_ACTION', 'Bot Action'), ('DEALER_PLAY', 'Dealer Play'), ('GAME_RESOLVE', 'Game Resolve')], db_index=True, max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.game')),
            ],
            options={
                'verbose_name': 'Game Event',
                'verbose_name_plural': 'Game Events',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='game.table'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Current chip balance. Can be negative.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'indexes': [models.Index(fields=['-balance'], name='userprofile_balance_desc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['player', 'status'], name='game_player_status_idx'),
        ),
    ]
