# Generated by Django 4.2.30 on 2026-05-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='left_at',
            field=models.DateTimeField(blank=True, help_text='Set when the player explicitly leaves a mid-hand game. Implies LOSE outcome.', null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='shoe_state',
            field=models.JSONField(default=list, help_text='Remaining cards in the shared 4-deck shoe. Populated by seed_tables.'),
        ),
    ]
