# Generated by Django 4.2.30 on 2026-05-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_side_bets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='shoe_state',
            field=models.JSONField(default=list, help_text="Remaining cards in the shared 6-deck shoe (includes 'CUT' sentinel). Populated by seed_tables."),
        ),
    ]
